services:
  db:
    image: mysql:9.6.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"

volumes:
  mysql_data: {}